title: Hatch website under construction
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "hatch.ga" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

twitter:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Hatchpay
  link: "https://twitter.com/Hatchpay"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: []

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Hatchpay

# Build settings
markdown: kramdown
permalink: pretty
